### ISSUE TITLE
Valid BIP39 from clues

### ISSUE THREAD

**Issue by andreicon** [iesta/1BTCPuzzle#1]
The ones you listed are not valid, they may generate a key on iancoleman's site, but the minimum is 12 words for the string to be a valid bip39 mnemonic seed

**Comment by iesta** [comment]
Yes i know that. 
It was meant to show that there are literally billions of combinations and that derivation works with 3 words. Who know of OP knew the 12 words limit :-)
Anyway it's useless so i will remove this part.
Thx
